---
:concurrency: 1
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
  - [high_priority, 2]
:max_retries: 5
:schedule:
  sgap_download_data_job:
    cron: '0 2 * * 7'
    class: SgapDownloadDataJob
  #bis_download_data_job:
    #cron: '0 2 * * 7'
    #cron: '0 0 1 * *'    
    #class: BisDownloadDataJob
  #bis_process_download_data_job:
    #cron: '0 3 * * 7'
    #cron: '0 2 1 * *'
    #class: BisProcessDownloadDataJob    
  gamification_hourly_job:
    cron: '0 * * * *'
    class: GamificationHourlyJob
  gamification_monthly_job:
    cron: '30 0 1 * *'
    class: GamificationMonthlyJob
  reportings_data_job:
    cron: '10 * * * *'
    class: ReportingsDataJob
  #all_reportings_data_job:
  #  cron: '15 1 * * *'
  #  class: AllReportingsDataJob    